/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CatalogCategoryUpdateQueryAsSubResourceAttributes } from './catalog-category-update-query-as-sub-resource-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships } from './get-catalog-item-create-job-response-collection-with-included-section-data-inner-relationships';

/**
 * 
 * @export
 * @interface CatalogCategoryUpdateQueryAsSubResource
 */
export interface CatalogCategoryUpdateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogCategoryUpdateQueryAsSubResource
     */
    'type': CatalogCategoryUpdateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CatalogCategoryUpdateQueryAsSubResource
     */
    'id': string;
    /**
     * 
     * @type {CatalogCategoryUpdateQueryAsSubResourceAttributes}
     * @memberof CatalogCategoryUpdateQueryAsSubResource
     */
    'attributes': CatalogCategoryUpdateQueryAsSubResourceAttributes;
    /**
     * 
     * @type {GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof CatalogCategoryUpdateQueryAsSubResource
     */
    'relationships'?: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships;
}

export const CatalogCategoryUpdateQueryAsSubResourceTypeEnum = {
    catalog_category: 'catalog-category'
} as const;

export type CatalogCategoryUpdateQueryAsSubResourceTypeEnum = typeof CatalogCategoryUpdateQueryAsSubResourceTypeEnum[keyof typeof CatalogCategoryUpdateQueryAsSubResourceTypeEnum];


