/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CatalogItemUpdateJobCreateQueryAsSubResourceAttributes } from './catalog-item-update-job-create-query-as-sub-resource-attributes';

/**
 * 
 * @export
 * @interface CatalogItemUpdateJobCreateQueryAsSubResource
 */
export interface CatalogItemUpdateJobCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogItemUpdateJobCreateQueryAsSubResource
     */
    'type': CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {CatalogItemUpdateJobCreateQueryAsSubResourceAttributes}
     * @memberof CatalogItemUpdateJobCreateQueryAsSubResource
     */
    'attributes': CatalogItemUpdateJobCreateQueryAsSubResourceAttributes;
}

export const CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum = {
    catalog_item_bulk_update_job: 'catalog-item-bulk-update-job'
} as const;

export type CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum = typeof CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum[keyof typeof CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum];


