/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CatalogVariantCreateQueryAsSubResourceAttributes } from './catalog-variant-create-query-as-sub-resource-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships } from './get-catalog-item-create-job-response-collection-with-included-section-data-inner-relationships';

/**
 * 
 * @export
 * @interface CatalogVariantCreateQueryAsSubResource
 */
export interface CatalogVariantCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResource
     */
    'type': CatalogVariantCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {CatalogVariantCreateQueryAsSubResourceAttributes}
     * @memberof CatalogVariantCreateQueryAsSubResource
     */
    'attributes': CatalogVariantCreateQueryAsSubResourceAttributes;
    /**
     * 
     * @type {GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof CatalogVariantCreateQueryAsSubResource
     */
    'relationships'?: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships;
}

export const CatalogVariantCreateQueryAsSubResourceTypeEnum = {
    catalog_variant: 'catalog-variant'
} as const;

export type CatalogVariantCreateQueryAsSubResourceTypeEnum = typeof CatalogVariantCreateQueryAsSubResourceTypeEnum[keyof typeof CatalogVariantCreateQueryAsSubResourceTypeEnum];


