/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CatalogItemUpdateQueryAsSubResourceAttributes
 */
export interface CatalogItemUpdateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {string}
     * @memberof CatalogItemUpdateQueryAsSubResourceAttributes
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemUpdateQueryAsSubResourceAttributes
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemUpdateQueryAsSubResourceAttributes
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemUpdateQueryAsSubResourceAttributes
     */
    'image_full_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemUpdateQueryAsSubResourceAttributes
     */
    'image_thumbnail_url'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogItemUpdateQueryAsSubResourceAttributes
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CatalogItemUpdateQueryAsSubResourceAttributes
     */
    'custom_metadata'?: object;
    /**
     * 
     * @type {boolean}
     * @memberof CatalogItemUpdateQueryAsSubResourceAttributes
     */
    'published'?: boolean;
}

