/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CatalogVariantDeleteQueryAsSubResource
 */
export interface CatalogVariantDeleteQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantDeleteQueryAsSubResource
     */
    'type': CatalogVariantDeleteQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantDeleteQueryAsSubResource
     */
    'id': string;
}

export const CatalogVariantDeleteQueryAsSubResourceTypeEnum = {
    catalog_variant: 'catalog-variant'
} as const;

export type CatalogVariantDeleteQueryAsSubResourceTypeEnum = typeof CatalogVariantDeleteQueryAsSubResourceTypeEnum[keyof typeof CatalogVariantDeleteQueryAsSubResourceTypeEnum];


