/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CatalogVariantUpdateQueryAsSubResourceAttributes } from './catalog-variant-update-query-as-sub-resource-attributes';

/**
 * 
 * @export
 * @interface CatalogVariantUpdateQueryAsSubResource
 */
export interface CatalogVariantUpdateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantUpdateQueryAsSubResource
     */
    'type': CatalogVariantUpdateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantUpdateQueryAsSubResource
     */
    'id': string;
    /**
     * 
     * @type {CatalogVariantUpdateQueryAsSubResourceAttributes}
     * @memberof CatalogVariantUpdateQueryAsSubResource
     */
    'attributes': CatalogVariantUpdateQueryAsSubResourceAttributes;
}

export const CatalogVariantUpdateQueryAsSubResourceTypeEnum = {
    catalog_variant: 'catalog-variant'
} as const;

export type CatalogVariantUpdateQueryAsSubResourceTypeEnum = typeof CatalogVariantUpdateQueryAsSubResourceTypeEnum[keyof typeof CatalogVariantUpdateQueryAsSubResourceTypeEnum];


