/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CatalogItemCreateQueryAsSubResourceAttributes
 */
export interface CatalogItemCreateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'external_id': string;
    /**
     * The integration type. Currently, this can only be set to $custom (and defaults to $custom if not included in the payload).
     * @type {string}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'integration_type'?: CatalogItemCreateQueryAsSubResourceAttributesIntegrationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'catalog_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'image_full_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'image_thumbnail_url'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'custom_metadata'?: object;
    /**
     * 
     * @type {boolean}
     * @memberof CatalogItemCreateQueryAsSubResourceAttributes
     */
    'published'?: boolean;
}

export const CatalogItemCreateQueryAsSubResourceAttributesIntegrationTypeEnum = {
    custom: '$custom'
} as const;

export type CatalogItemCreateQueryAsSubResourceAttributesIntegrationTypeEnum = typeof CatalogItemCreateQueryAsSubResourceAttributesIntegrationTypeEnum[keyof typeof CatalogItemCreateQueryAsSubResourceAttributesIntegrationTypeEnum];


