/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CatalogItemDeleteJobCreateQueryAsSubResourceAttributes } from './catalog-item-delete-job-create-query-as-sub-resource-attributes';

/**
 * 
 * @export
 * @interface CatalogItemDeleteJobCreateQueryAsSubResource
 */
export interface CatalogItemDeleteJobCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDeleteJobCreateQueryAsSubResource
     */
    'type': CatalogItemDeleteJobCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {CatalogItemDeleteJobCreateQueryAsSubResourceAttributes}
     * @memberof CatalogItemDeleteJobCreateQueryAsSubResource
     */
    'attributes': CatalogItemDeleteJobCreateQueryAsSubResourceAttributes;
}

export const CatalogItemDeleteJobCreateQueryAsSubResourceTypeEnum = {
    catalog_item_bulk_delete_job: 'catalog-item-bulk-delete-job'
} as const;

export type CatalogItemDeleteJobCreateQueryAsSubResourceTypeEnum = typeof CatalogItemDeleteJobCreateQueryAsSubResourceTypeEnum[keyof typeof CatalogItemDeleteJobCreateQueryAsSubResourceTypeEnum];


