/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MetricCreateQuery } from './metric-create-query';

/**
 * 
 * @export
 * @interface EventCreateQueryAsSubResourceAttributes
 */
export interface EventCreateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {object}
     * @memberof EventCreateQueryAsSubResourceAttributes
     */
    'profile': object;
    /**
     * 
     * @type {MetricCreateQuery}
     * @memberof EventCreateQueryAsSubResourceAttributes
     */
    'metric': MetricCreateQuery;
    /**
     * 
     * @type {object}
     * @memberof EventCreateQueryAsSubResourceAttributes
     */
    'properties': object;
    /**
     * 
     * @type {string}
     * @memberof EventCreateQueryAsSubResourceAttributes
     */
    'time'?: string;
    /**
     * 
     * @type {number}
     * @memberof EventCreateQueryAsSubResourceAttributes
     */
    'value'?: number;
    /**
     * 
     * @type {string}
     * @memberof EventCreateQueryAsSubResourceAttributes
     */
    'unique_id'?: string;
}

