/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner
 */
export interface GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner
     */
    'type': GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner
     */
    'id': string;
}

export const GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum = {
    profile: 'profile'
} as const;

export type GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum = typeof GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum[keyof typeof GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum];


