/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CatalogJobErrorPayload } from './catalog-job-error-payload';

/**
 * 
 * @export
 * @interface GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
 */
export interface GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    'job_id': string;
    /**
     * The valid top level statuses for an asynchronous query
     * @type {string}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    'status': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    'created_at': string;
    /**
     * 
     * @type {number}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    'total_count': number;
    /**
     * 
     * @type {number}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    'completed_count': number;
    /**
     * 
     * @type {number}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    'failed_count': number;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    'completed_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    'expires_at'?: string;
    /**
     * 
     * @type {Array<CatalogJobErrorPayload>}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    'errors'?: Array<CatalogJobErrorPayload>;
}

export const GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesStatusEnum = {
    complete: 'complete',
    processing: 'processing',
    queued: 'queued'
} as const;

export type GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesStatusEnum = typeof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesStatusEnum[keyof typeof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesStatusEnum];


