/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogCategoryResponseCollectionDataInnerAttributes } from './get-catalog-category-response-collection-data-inner-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';

/**
 * 
 * @export
 * @interface GetCatalogCategoryResponseCollectionDataInner
 */
export interface GetCatalogCategoryResponseCollectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogCategoryResponseCollectionDataInner
     */
    'type': GetCatalogCategoryResponseCollectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogCategoryResponseCollectionDataInner
     */
    'id': string;
    /**
     * 
     * @type {GetCatalogCategoryResponseCollectionDataInnerAttributes}
     * @memberof GetCatalogCategoryResponseCollectionDataInner
     */
    'attributes': GetCatalogCategoryResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetCatalogCategoryResponseCollectionDataInner
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}

export const GetCatalogCategoryResponseCollectionDataInnerTypeEnum = {
    catalog_category: 'catalog-category'
} as const;

export type GetCatalogCategoryResponseCollectionDataInnerTypeEnum = typeof GetCatalogCategoryResponseCollectionDataInnerTypeEnum[keyof typeof GetCatalogCategoryResponseCollectionDataInnerTypeEnum];


