/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetCatalogCategoryItemListResponseCollectionDataInner
 */
export interface GetCatalogCategoryItemListResponseCollectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogCategoryItemListResponseCollectionDataInner
     */
    'type': GetCatalogCategoryItemListResponseCollectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogCategoryItemListResponseCollectionDataInner
     */
    'id': string;
}

export const GetCatalogCategoryItemListResponseCollectionDataInnerTypeEnum = {
    catalog_item: 'catalog-item'
} as const;

export type GetCatalogCategoryItemListResponseCollectionDataInnerTypeEnum = typeof GetCatalogCategoryItemListResponseCollectionDataInnerTypeEnum[keyof typeof GetCatalogCategoryItemListResponseCollectionDataInnerTypeEnum];


