/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogVariantResponseCollectionDataInnerAttributes } from './get-catalog-variant-response-collection-data-inner-attributes';

/**
 * 
 * @export
 * @interface GetCatalogVariantResponseCollectionDataInner
 */
export interface GetCatalogVariantResponseCollectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogVariantResponseCollectionDataInner
     */
    'type': GetCatalogVariantResponseCollectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogVariantResponseCollectionDataInner
     */
    'id': string;
    /**
     * 
     * @type {GetCatalogVariantResponseCollectionDataInnerAttributes}
     * @memberof GetCatalogVariantResponseCollectionDataInner
     */
    'attributes': GetCatalogVariantResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetCatalogVariantResponseCollectionDataInner
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}

export const GetCatalogVariantResponseCollectionDataInnerTypeEnum = {
    catalog_variant: 'catalog-variant'
} as const;

export type GetCatalogVariantResponseCollectionDataInnerTypeEnum = typeof GetCatalogVariantResponseCollectionDataInnerTypeEnum[keyof typeof GetCatalogVariantResponseCollectionDataInnerTypeEnum];


