/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetFlowResponseCollectionWithIncludedSectionDataInnerRelationshipsFlowActionsDataInner
 */
export interface GetFlowResponseCollectionWithIncludedSectionDataInnerRelationshipsFlowActionsDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetFlowResponseCollectionWithIncludedSectionDataInnerRelationshipsFlowActionsDataInner
     */
    'type': GetFlowResponseCollectionWithIncludedSectionDataInnerRelationshipsFlowActionsDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetFlowResponseCollectionWithIncludedSectionDataInnerRelationshipsFlowActionsDataInner
     */
    'id': string;
}

export const GetFlowResponseCollectionWithIncludedSectionDataInnerRelationshipsFlowActionsDataInnerTypeEnum = {
    flow_action: 'flow-action'
} as const;

export type GetFlowResponseCollectionWithIncludedSectionDataInnerRelationshipsFlowActionsDataInnerTypeEnum = typeof GetFlowResponseCollectionWithIncludedSectionDataInnerRelationshipsFlowActionsDataInnerTypeEnum[keyof typeof GetFlowResponseCollectionWithIncludedSectionDataInnerRelationshipsFlowActionsDataInnerTypeEnum];


