/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes } from './get-catalog-item-create-job-response-collection-with-included-section-data-inner-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships } from './get-catalog-item-create-job-response-collection-with-included-section-data-inner-relationships';
// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';

/**
 * 
 * @export
 * @interface GetCatalogItemDeleteJobResponseCollectionDataInner
 */
export interface GetCatalogItemDeleteJobResponseCollectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemDeleteJobResponseCollectionDataInner
     */
    'type': GetCatalogItemDeleteJobResponseCollectionDataInnerTypeEnum;
    /**
     * 
     * @type {GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof GetCatalogItemDeleteJobResponseCollectionDataInner
     */
    'attributes': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof GetCatalogItemDeleteJobResponseCollectionDataInner
     */
    'relationships'?: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetCatalogItemDeleteJobResponseCollectionDataInner
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}

export const GetCatalogItemDeleteJobResponseCollectionDataInnerTypeEnum = {
    catalog_item_bulk_delete_job: 'catalog-item-bulk-delete-job'
} as const;

export type GetCatalogItemDeleteJobResponseCollectionDataInnerTypeEnum = typeof GetCatalogItemDeleteJobResponseCollectionDataInnerTypeEnum[keyof typeof GetCatalogItemDeleteJobResponseCollectionDataInnerTypeEnum];


