/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetFlowResponseCollectionWithIncludedSectionDataInnerAttributes } from './get-flow-response-collection-with-included-section-data-inner-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { GetFlowResponseCollectionWithIncludedSectionDataInnerRelationships } from './get-flow-response-collection-with-included-section-data-inner-relationships';
// May contain unused imports in some cases
// @ts-ignore
import { IncludedFlowActions } from './included-flow-actions';

/**
 * 
 * @export
 * @interface GetFlowResponseCollectionWithIncludedSectionDataInner
 */
export interface GetFlowResponseCollectionWithIncludedSectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetFlowResponseCollectionWithIncludedSectionDataInner
     */
    'type': GetFlowResponseCollectionWithIncludedSectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetFlowResponseCollectionWithIncludedSectionDataInner
     */
    'id': string;
    /**
     * 
     * @type {GetFlowResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof GetFlowResponseCollectionWithIncludedSectionDataInner
     */
    'attributes': GetFlowResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetFlowResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof GetFlowResponseCollectionWithIncludedSectionDataInner
     */
    'relationships'?: GetFlowResponseCollectionWithIncludedSectionDataInnerRelationships;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetFlowResponseCollectionWithIncludedSectionDataInner
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
    /**
     * 
     * @type {Array<IncludedFlowActions>}
     * @memberof GetFlowResponseCollectionWithIncludedSectionDataInner
     */
    'included'?: Array<IncludedFlowActions>;
}

export const GetFlowResponseCollectionWithIncludedSectionDataInnerTypeEnum = {
    flow: 'flow'
} as const;

export type GetFlowResponseCollectionWithIncludedSectionDataInnerTypeEnum = typeof GetFlowResponseCollectionWithIncludedSectionDataInnerTypeEnum[keyof typeof GetFlowResponseCollectionWithIncludedSectionDataInnerTypeEnum];


