/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetFlowActionResponseCollectionDataInnerAttributesTrackingOptions } from './get-flow-action-response-collection-data-inner-attributes-tracking-options';
// May contain unused imports in some cases
// @ts-ignore
import { SMSRenderOptions } from './smsrender-options';
// May contain unused imports in some cases
// @ts-ignore
import { SendOptions } from './send-options';

/**
 * 
 * @export
 * @interface GetFlowActionResponseCollectionDataInnerAttributes
 */
export interface GetFlowActionResponseCollectionDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof GetFlowActionResponseCollectionDataInnerAttributes
     */
    'action_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFlowActionResponseCollectionDataInnerAttributes
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFlowActionResponseCollectionDataInnerAttributes
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFlowActionResponseCollectionDataInnerAttributes
     */
    'updated'?: string;
    /**
     * 
     * @type {object}
     * @memberof GetFlowActionResponseCollectionDataInnerAttributes
     */
    'settings'?: object;
    /**
     * 
     * @type {GetFlowActionResponseCollectionDataInnerAttributesTrackingOptions}
     * @memberof GetFlowActionResponseCollectionDataInnerAttributes
     */
    'tracking_options'?: GetFlowActionResponseCollectionDataInnerAttributesTrackingOptions;
    /**
     * 
     * @type {SendOptions}
     * @memberof GetFlowActionResponseCollectionDataInnerAttributes
     */
    'send_options'?: SendOptions;
    /**
     * 
     * @type {SMSRenderOptions}
     * @memberof GetFlowActionResponseCollectionDataInnerAttributes
     */
    'render_options'?: SMSRenderOptions;
}

