/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetEventResponseCollectionWithIncludedSectionDataInnerAttributes } from './get-event-response-collection-with-included-section-data-inner-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { GetEventResponseCollectionWithIncludedSectionDataInnerIncludedInner } from './get-event-response-collection-with-included-section-data-inner-included-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GetEventResponseCollectionWithIncludedSectionDataInnerRelationships } from './get-event-response-collection-with-included-section-data-inner-relationships';

/**
 * 
 * @export
 * @interface GetEventResponseCollectionWithIncludedSectionDataInner
 */
export interface GetEventResponseCollectionWithIncludedSectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInner
     */
    'type': GetEventResponseCollectionWithIncludedSectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInner
     */
    'id': string;
    /**
     * 
     * @type {GetEventResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInner
     */
    'attributes': GetEventResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetEventResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInner
     */
    'relationships'?: GetEventResponseCollectionWithIncludedSectionDataInnerRelationships;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInner
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
    /**
     * 
     * @type {Array<GetEventResponseCollectionWithIncludedSectionDataInnerIncludedInner>}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInner
     */
    'included'?: Array<GetEventResponseCollectionWithIncludedSectionDataInnerIncludedInner>;
}

export const GetEventResponseCollectionWithIncludedSectionDataInnerTypeEnum = {
    event: 'event'
} as const;

export type GetEventResponseCollectionWithIncludedSectionDataInnerTypeEnum = typeof GetEventResponseCollectionWithIncludedSectionDataInnerTypeEnum[keyof typeof GetEventResponseCollectionWithIncludedSectionDataInnerTypeEnum];


