/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetCatalogItems4XXResponseErrorsInnerSource
 */
export interface GetCatalogItems4XXResponseErrorsInnerSource {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItems4XXResponseErrorsInnerSource
     */
    'pointer'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItems4XXResponseErrorsInnerSource
     */
    'parameter'?: string;
}

