/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetProfileResponseCollectionDataInnerAttributes } from './get-profile-response-collection-data-inner-attributes';

/**
 * 
 * @export
 * @interface GetProfileResponseCollectionDataInner
 */
export interface GetProfileResponseCollectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInner
     */
    'type': GetProfileResponseCollectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInner
     */
    'id': string;
    /**
     * 
     * @type {GetProfileResponseCollectionDataInnerAttributes}
     * @memberof GetProfileResponseCollectionDataInner
     */
    'attributes': GetProfileResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetProfileResponseCollectionDataInner
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}

export const GetProfileResponseCollectionDataInnerTypeEnum = {
    profile: 'profile'
} as const;

export type GetProfileResponseCollectionDataInnerTypeEnum = typeof GetProfileResponseCollectionDataInnerTypeEnum[keyof typeof GetProfileResponseCollectionDataInnerTypeEnum];


