/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetFlowMessageResponseCollectionDataInnerAttributes } from './get-flow-message-response-collection-data-inner-attributes';

/**
 * 
 * @export
 * @interface IncludedFlowMessages
 */
export interface IncludedFlowMessages {
    /**
     * 
     * @type {string}
     * @memberof IncludedFlowMessages
     */
    'type': IncludedFlowMessagesTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IncludedFlowMessages
     */
    'id': string;
    /**
     * 
     * @type {GetFlowMessageResponseCollectionDataInnerAttributes}
     * @memberof IncludedFlowMessages
     */
    'attributes': GetFlowMessageResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof IncludedFlowMessages
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}

export const IncludedFlowMessagesTypeEnum = {
    flow_message: 'flow-message'
} as const;

export type IncludedFlowMessagesTypeEnum = typeof IncludedFlowMessagesTypeEnum[keyof typeof IncludedFlowMessagesTypeEnum];


