/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetFlowActionResponseCollectionDataInnerAttributes } from './get-flow-action-response-collection-data-inner-attributes';

/**
 * 
 * @export
 * @interface IncludedFlowAction
 */
export interface IncludedFlowAction {
    /**
     * 
     * @type {string}
     * @memberof IncludedFlowAction
     */
    'type': IncludedFlowActionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IncludedFlowAction
     */
    'id': string;
    /**
     * 
     * @type {GetFlowActionResponseCollectionDataInnerAttributes}
     * @memberof IncludedFlowAction
     */
    'attributes': GetFlowActionResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof IncludedFlowAction
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}

export const IncludedFlowActionTypeEnum = {
    flow_action: 'flow-action'
} as const;

export type IncludedFlowActionTypeEnum = typeof IncludedFlowActionTypeEnum[keyof typeof IncludedFlowActionTypeEnum];


