/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetMetricResponseCollectionDataInnerAttributes } from './get-metric-response-collection-data-inner-attributes';

/**
 * 
 * @export
 * @interface IncludedMetrics
 */
export interface IncludedMetrics {
    /**
     * 
     * @type {string}
     * @memberof IncludedMetrics
     */
    'type': IncludedMetricsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IncludedMetrics
     */
    'id': string;
    /**
     * 
     * @type {GetMetricResponseCollectionDataInnerAttributes}
     * @memberof IncludedMetrics
     */
    'attributes': GetMetricResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof IncludedMetrics
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}

export const IncludedMetricsTypeEnum = {
    metric: 'metric'
} as const;

export type IncludedMetricsTypeEnum = typeof IncludedMetricsTypeEnum[keyof typeof IncludedMetricsTypeEnum];


