/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ListCreateQueryAsSubResourceAttributes } from './list-create-query-as-sub-resource-attributes';

/**
 * 
 * @export
 * @interface ListCreateQueryAsSubResource
 */
export interface ListCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof ListCreateQueryAsSubResource
     */
    'type': ListCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {ListCreateQueryAsSubResourceAttributes}
     * @memberof ListCreateQueryAsSubResource
     */
    'attributes': ListCreateQueryAsSubResourceAttributes;
}

export const ListCreateQueryAsSubResourceTypeEnum = {
    list: 'list'
} as const;

export type ListCreateQueryAsSubResourceTypeEnum = typeof ListCreateQueryAsSubResourceTypeEnum[keyof typeof ListCreateQueryAsSubResourceTypeEnum];


