/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MetricAggregateQueryAsSubResourceAttributes
 */
export interface MetricAggregateQueryAsSubResourceAttributes {
  /**
   *
   * @type {string}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  metric_id: string;
  /**
   *
   * @type {Array<string>}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  measurements: Array<MetricAggregateQueryAsSubResourceAttributesMeasurementsEnum>;
  /**
   * Supported intervals for bucketing query results by time
   * @type {string}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  interval: MetricAggregateQueryAsSubResourceAttributesIntervalEnum;
  /**
   *
   * @type {number}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  page_size?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  by?: Array<MetricAggregateQueryAsSubResourceAttributesByEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  return_fields?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  filter: Array<string>;
  /**
   *
   * @type {string}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  timezone: string;
  /**
   *
   * @type {string}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  sort?: MetricAggregateQueryAsSubResourceAttributesSortEnum;
  /**
   *
   * @type {string}
   * @memberof MetricAggregateQueryAsSubResourceAttributes
   */
  page_cursor?: string;
}

export const MetricAggregateQueryAsSubResourceAttributesMeasurementsEnum = {
  count: "count",
  sum_value: "sum_value",
  unique: "unique",
} as const;

export type MetricAggregateQueryAsSubResourceAttributesMeasurementsEnum =
  typeof MetricAggregateQueryAsSubResourceAttributesMeasurementsEnum[keyof typeof MetricAggregateQueryAsSubResourceAttributesMeasurementsEnum];
export const MetricAggregateQueryAsSubResourceAttributesIntervalEnum = {
  day: "day",
  hour: "hour",
  month: "month",
  week: "week",
} as const;

export type MetricAggregateQueryAsSubResourceAttributesIntervalEnum =
  typeof MetricAggregateQueryAsSubResourceAttributesIntervalEnum[keyof typeof MetricAggregateQueryAsSubResourceAttributesIntervalEnum];
export const MetricAggregateQueryAsSubResourceAttributesByEnum = {
  attributed_channel: "$attributed_channel",
  attributed_flow: "$attributed_flow",
  attributed_message: "$attributed_message",
  attributed_variation: "$attributed_variation",
  campaign_channel: "$campaign_channel",
  flow: "$flow",
  flow_channel: "$flow_channel",
  message: "$message",
  message_send_cohort: "$message_send_cohort",
  variation: "$variation",
  variation_send_cohort: "$variation_send_cohort",
  Bounce_Type: "Bounce Type",
  Campaign_Name: "Campaign Name",
  Client_Canonical: "Client Canonical",
  Client_Name: "Client Name",
  Client_Type: "Client Type",
  Email_Domain: "Email Domain",
  Failure_Source: "Failure Source",
  Failure_Type: "Failure Type",
  From_Number: "From Number",
  From_Phone_Region: "From Phone Region",
  List: "List",
  Message_Name: "Message Name",
  Message_Type: "Message Type",
  Method: "Method",
  Subject: "Subject",
  To_Number: "To Number",
  To_Phone_Region: "To Phone Region",
  URL: "URL",
  form_id: "form_id",
} as const;

export type MetricAggregateQueryAsSubResourceAttributesByEnum =
  typeof MetricAggregateQueryAsSubResourceAttributesByEnum[keyof typeof MetricAggregateQueryAsSubResourceAttributesByEnum];
export const MetricAggregateQueryAsSubResourceAttributesSortEnum = {
  attributed_channel: "$attributed_channel",
  attributed_channel_descending: "-$attributed_channel",
  attributed_flow: "$attributed_flow",
  attributed_flow_descending: "-$attributed_flow",
  attributed_message: "$attributed_message",
  attributed_message_descending: "-$attributed_message",
  attributed_variation: "$attributed_variation",
  attributed_variation_descending: "-$attributed_variation",
  campaign_channel: "$campaign_channel",
  campaign_channel_descending: "-$campaign_channel",
  flow: "$flow",
  flow_descending: "-$flow",
  flow_channel: "$flow_channel",
  flow_channel_descending: "-$flow_channel",
  message: "$message",
  message_descending: "-$message",
  message_send_cohort: "$message_send_cohort",
  message_send_cohort_descending: "-$message_send_cohort",
  variation: "$variation",
  variation_descending: "-$variation",
  variation_send_cohort: "$variation_send_cohort",
  variation_send_cohort_descending: "-$variation_send_cohort",
  Bounce_Type: "Bounce Type",
  Bounce_Type_descending: "-Bounce Type",
  Campaign_Name: "Campaign Name",
  Campaign_Name_descending: "-Campaign Name",
  Client_Canonical: "Client Canonical",
  Client_Canonical_descending: "-Client Canonical",
  Client_Name: "Client Name",
  Client_Name_descending: "-Client Name",
  Client_Type: "Client Type",
  Client_Type_descending: "-Client Type",
  Email_Domain: "Email Domain",
  Email_Domain_descending: "-Email Domain",
  Failure_Source: "Failure Source",
  Failure_Source_descending: "-Failure Source",
  Failure_Type: "Failure Type",
  Failure_Type_descending: "-Failure Type",
  From_Number: "From Number",
  From_Number_descending: "-From Number",
  From_Phone_Region: "From Phone Region",
  From_Phone_Region_descending: "-From Phone Region",
  List: "List",
  List_descending: "-List",
  Message_Name: "Message Name",
  Message_Name_descending: "-Message Name",
  Message_Type: "Message Type",
  Message_Type_descending: "-Message Type",
  Method: "Method",
  Method_descending: "-Method",
  Subject: "Subject",
  Subject_descending: "-Subject",
  To_Number: "To Number",
  To_Number_descending: "-To Number",
  To_Phone_Region: "To Phone Region",
  To_Phone_Region_descending: "-To Phone Region",
  URL: "URL",
  URL_descending: "-URL",
  count: "count",
  count_descending: "-count",
  form_id: "form_id",
  form_id_descending: "-form_id",
  sum_value: "sum_value",
  sum_value_descending: "-sum_value",
  unique: "unique",
  unique_descending: "-unique",
} as const;

export type MetricAggregateQueryAsSubResourceAttributesSortEnum =
  typeof MetricAggregateQueryAsSubResourceAttributesSortEnum[keyof typeof MetricAggregateQueryAsSubResourceAttributesSortEnum];
