/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OnsiteSubscriptionCreateQueryAsSubResourceAttributes
 */
export interface OnsiteSubscriptionCreateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {string}
     * @memberof OnsiteSubscriptionCreateQueryAsSubResourceAttributes
     */
    'list_id': string;
    /**
     * 
     * @type {string}
     * @memberof OnsiteSubscriptionCreateQueryAsSubResourceAttributes
     */
    'custom_source'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnsiteSubscriptionCreateQueryAsSubResourceAttributes
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnsiteSubscriptionCreateQueryAsSubResourceAttributes
     */
    'phone_number'?: string;
    /**
     * 
     * @type {object}
     * @memberof OnsiteSubscriptionCreateQueryAsSubResourceAttributes
     */
    'properties'?: object;
}

