/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes } from './get-catalog-item-response-collection-with-included-section-data-inner-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './get-catalog-item-response-collection-with-included-section-data-inner-links';

/**
 * 
 * @export
 * @interface PostCatalogItemResponseData
 */
export interface PostCatalogItemResponseData {
    /**
     * 
     * @type {string}
     * @memberof PostCatalogItemResponseData
     */
    'type': PostCatalogItemResponseDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PostCatalogItemResponseData
     */
    'id': string;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof PostCatalogItemResponseData
     */
    'attributes': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof PostCatalogItemResponseData
     */
    'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}

export const PostCatalogItemResponseDataTypeEnum = {
    catalog_item: 'catalog-item'
} as const;

export type PostCatalogItemResponseDataTypeEnum = typeof PostCatalogItemResponseDataTypeEnum[keyof typeof PostCatalogItemResponseDataTypeEnum];


