/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProfileCreateQueryAsSubResourceAttributes } from './profile-create-query-as-sub-resource-attributes';

/**
 * 
 * @export
 * @interface ProfilePartialUpdateQueryAsSubResource
 */
export interface ProfilePartialUpdateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof ProfilePartialUpdateQueryAsSubResource
     */
    'type': ProfilePartialUpdateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ProfilePartialUpdateQueryAsSubResource
     */
    'id': string;
    /**
     * 
     * @type {ProfileCreateQueryAsSubResourceAttributes}
     * @memberof ProfilePartialUpdateQueryAsSubResource
     */
    'attributes': ProfileCreateQueryAsSubResourceAttributes;
}

export const ProfilePartialUpdateQueryAsSubResourceTypeEnum = {
    profile: 'profile'
} as const;

export type ProfilePartialUpdateQueryAsSubResourceTypeEnum = typeof ProfilePartialUpdateQueryAsSubResourceTypeEnum[keyof typeof ProfilePartialUpdateQueryAsSubResourceTypeEnum];


