/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UtmParamInfo } from './utm-param-info';

/**
 * 
 * @export
 * @interface SMSTrackingOptions
 */
export interface SMSTrackingOptions {
    /**
     * 
     * @type {boolean}
     * @memberof SMSTrackingOptions
     */
    'add_utm': boolean;
    /**
     * 
     * @type {Array<UtmParamInfo>}
     * @memberof SMSTrackingOptions
     */
    'utm_params': Array<UtmParamInfo>;
}

