/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SubscriptionCreateJobCreateQueryAsSubResourceAttributes } from './subscription-create-job-create-query-as-sub-resource-attributes';

/**
 * 
 * @export
 * @interface SubscriptionCreateJobCreateQueryAsSubResource
 */
export interface SubscriptionCreateJobCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreateJobCreateQueryAsSubResource
     */
    'type': SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {SubscriptionCreateJobCreateQueryAsSubResourceAttributes}
     * @memberof SubscriptionCreateJobCreateQueryAsSubResource
     */
    'attributes': SubscriptionCreateJobCreateQueryAsSubResourceAttributes;
}

export const SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum = {
    profile_subscription_bulk_create_job: 'profile-subscription-bulk-create-job'
} as const;

export type SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum = typeof SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum[keyof typeof SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum];


