/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TemplateCreateQueryAsSubResourceAttributes
 */
export interface TemplateCreateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {string}
     * @memberof TemplateCreateQueryAsSubResourceAttributes
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof TemplateCreateQueryAsSubResourceAttributes
     */
    'editor_type': string;
    /**
     * 
     * @type {string}
     * @memberof TemplateCreateQueryAsSubResourceAttributes
     */
    'html'?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateCreateQueryAsSubResourceAttributes
     */
    'text'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TemplateCreateQueryAsSubResourceAttributes
     */
    'return_fields'?: Array<string>;
}

