/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TemplateCreateQueryAsSubResourceAttributes } from './template-create-query-as-sub-resource-attributes';

/**
 * 
 * @export
 * @interface TemplateCreateQueryAsSubResource
 */
export interface TemplateCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof TemplateCreateQueryAsSubResource
     */
    'type': TemplateCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {TemplateCreateQueryAsSubResourceAttributes}
     * @memberof TemplateCreateQueryAsSubResource
     */
    'attributes': TemplateCreateQueryAsSubResourceAttributes;
}

export const TemplateCreateQueryAsSubResourceTypeEnum = {
    template: 'template'
} as const;

export type TemplateCreateQueryAsSubResourceTypeEnum = typeof TemplateCreateQueryAsSubResourceTypeEnum[keyof typeof TemplateCreateQueryAsSubResourceTypeEnum];


